bawebauth/apps/bawebauth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views, methods

urlpatterns = (
    url(r'^$', views.show_home, name='show_home'),
    url(r'^dashboard/$', views.show_dashboard, name='show_dashboard'),
    url(r'^dashboard/device/(?P<device_id>\d+)/$', views.show_device, name='show_device'),
    url(r'^dashboard/device/(?P<device_id>\d+)/edit/$', views.edit_device, name='edit_device'),
    url(r'^dashboard/device/(?P<device_id>\d+)/switch/$', views.switch_device, name='switch_device'),
    url(r'^dashboard/device/(?P<device_id>\d+)/delete/$', views.delete_device, name='delete_device'),
    url(r'^dashboard/device/(?P<device_id>\d+)/delete/ask/$', views.delete_device_ask, name='delete_device_ask'),
)

urlpatterns += (
    url(r'^api/restful/user/auth/$', methods.auth_user, name='auth_user'),
    url(r'^api/restful/user/quit/$', methods.quit_user, name='quit_user'),
    url(r'^api/restful/device/create/$', methods.create_device, name='create_device'),
    url(r'^api/restful/device/delete/$', methods.delete_device, name='delete_device'),
    url(r'^api/restful/usage/push/$', methods.push_usage, name='push_usage'),
    url(r'^api/restful/usage/list/$', methods.list_usage, name='list_usage'),
    url(r'^api/restful/usage/sum/$', methods.device_usage, name='device_usage'),
)

urlpatterns += (
    url(r'^api/restful/usages\.(?P<format>\w+)$', methods.api_usages, name='api_usages'),
    url(r'^api/restful/device/(?P<device_id>\d+)/usages\.(?P<format>\w+)$', methods.api_device_usages, name='api_device_usages'),
)

bawebauth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = (
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('django.contrib.auth.urls')),
    url(r'', include('bawebauth.apps.bawebauth.urls', namespace='bawebauth')),
)

bawebauth/apps/bawebauth/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.cache import cache
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from .fields import PositiveBigIntegerField

class Device(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(_('name'), max_length=100)
    ident = models.CharField(_('ident'), max_length=40)
    crdate = models.DateTimeField(_('date created'), auto_now_add=True)
    tstamp = models.DateTimeField(_('date edited'), auto_now=True)
    active = models.BooleanField(_('active'), default=False)
    enabled = models.BooleanField(_('enabled'), default=False)

    def __str__(self):
        return self.name

    @property
    def usages(self):
        return self.usage_set.order_by('crdate')

    @property
    def last_usage(self):
        return self.usage_set.latest('crdate')

    @property
    def send(self):
        return self.usage_set.aggregate(send=models.Sum('send'))['send']

    @property
    def received(self):
        return self.usage_set.aggregate(received=models.Sum('received'))['received']

    @property
    def total(self):
        return self.send + self.received

class Usage(models.Model):
    device = models.ForeignKey(Device)
    send = PositiveBigIntegerField(_('bytes send'))
    received = PositiveBigIntegerField(_('bytes received'))
    crdate = models.DateTimeField(_('date created'), auto_now_add=True)

    def __str__(self):
        return '%s %s+ %s-' % (self.crdate, self.send, self.received)

bawebauth/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.cache import cache
from django.contrib.auth.models import User
from bawebauth.decorators import cache_property
from bawebauth.fields import PositiveBigIntegerField
from django.utils.translation import ugettext_lazy as _

class Device(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(_('name'), max_length=100)
    ident = models.CharField(_('ident'), max_length=40)
    crdate = models.DateTimeField(_('date created'), auto_now_add=True)
    tstamp = models.DateTimeField(_('date edited'), auto_now=True)
    active = models.BooleanField(_('active'), default=False)
    enabled = models.BooleanField(_('enabled'), default=False)
    
    def __unicode__(self):
        return self.name

    @cache_property
    def usages(self):
        return self.usage_set.order_by('crdate')

    @cache_property
    def last_usage(self):
        return self.usage_set.latest('crdate')

    @cache_property
    def send(self):
        return self.usage_set.aggregate(send=models.Sum('send'))['send']

    @cache_property
    def received(self):
        return self.usage_set.aggregate(received=models.Sum('received'))['received']

    @cache_property
    def total(self):
        return self.send + self.received

class Usage(models.Model):
    device = models.ForeignKey(Device)
    send = PositiveBigIntegerField(_('bytes send'))
    received = PositiveBigIntegerField(_('bytes received'))
    crdate = models.DateTimeField(_('date created'), auto_now_add=True)
    
    def __unicode__(self):
        return u'%s %s+ %s-' % (self.crdate, self.send, self.received)

bawebauth/apps/bawebauth/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Device

class DeviceForm(forms.ModelForm):
    name = forms.CharField(required=True,
        label='Name', help_text='Type in a client name.')

    class Meta:
        model = Device
        fields = ['name']

bawebauth/forms.py
# -*- coding: utf-8 -*-
from django import forms
from bawebauth.models import Device

class DeviceForm(forms.ModelForm):
    name = forms.CharField(required=True,
        label='Name', help_text='Type in a client name.')

    class Meta:
        model = Device
        fields = ['name']

bawebauth/apps/bawebauth/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404
from django.template import RequestContext
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from .forms import DeviceForm
from .models import Device, Usage

def show_home(request):
    return render(request, 'show_home.html')

@login_required
def show_dashboard(request):
    devices = Device.objects.all().filter(user=request.user).order_by('name')

    template_values = {
        'devices': devices,
    }

    return render(request, 'show_dashboard.html', template_values)

@login_required
def show_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)

    template_values = {
        'devices': devices,
        'device': device,
    }

    return render(request, 'show_dashboard.html', template_values)

@login_required
def edit_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)
    edit_form = DeviceForm(instance=device, data=request.POST if request.method == 'POST' else None)

    if edit_form.is_valid():
        device = edit_form.save(commit=False)
        device.user = request.user
        device.save()
        return HttpResponseRedirect(reverse('bawebauth:show_device', kwargs={'device_id': device.id}))

    template_values = {
        'devices': devices,
        'device': device,
        'device_edit_form': edit_form,
    }

    return render(request, 'show_dashboard.html', template_values)

@login_required
def switch_device(request, device_id):
    device = get_object_or_404(Device, user=request.user, id=device_id)
    device.enabled = not(device.enabled)
    device.active = True
    device.save()

    messages.success(request, 'Switched device "%s" %s!' % (device, 'on' if device.enabled else 'off'))

    return HttpResponseRedirect(reverse('bawebauth:show_device', kwargs={'device_id': device.id}))

@login_required
def delete_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)
    device.delete()

    messages.success(request, 'Deleted device "%s" from your Dashboard!' % device)

    template_values = {
        'devices': devices,
    }

    return render(request, 'show_dashboard.html', template_values)

@login_required
def delete_device_ask(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)

    button = '<a class="ym-button ym-delete ym-danger float-right" href="%s" title="Yes">Yes</a>' % reverse('bawebauth:delete_device', kwargs={'device_id': device.id})
    messages.warning(request, '%sDo you want to delete device "%s"?' % (button, device))

    template_values = {
        'devices': devices,
    }

    return render(request, 'show_dashboard.html', template_values)

bawebauth/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404
from bawebauth.forms import DeviceForm
from bawebauth.models import Device, Usage
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib import messages

def show_home(request):
    return render_to_response('show_home.html', context_instance=RequestContext(request))

@login_required
def show_dashboard(request):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    
    template_values = {
        'devices': devices,
    }

    return render_to_response('show_dashboard.html', template_values, context_instance=RequestContext(request))

@login_required
def show_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)

    template_values = {
        'devices': devices,
        'device': device,
    }
    
    return render_to_response('show_dashboard.html', template_values, context_instance=RequestContext(request))

@login_required
def edit_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)
    edit_form = DeviceForm(instance=device, data=request.POST if request.method == 'POST' else None)

    if edit_form.is_valid():
        device = edit_form.save(commit=False)
        device.user = request.user
        device.save()
        return HttpResponseRedirect(reverse('bawebauth.views.show_device', kwargs={'device_id': device.id}))
    
    template_values = {
        'devices': devices,
        'device': device,
        'device_edit_form': edit_form,
    }
    
    return render_to_response('show_dashboard.html', template_values, context_instance=RequestContext(request))

@login_required
def switch_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)
    device.enabled = not(device.enabled)
    device.active = True
    device.save()
    
    messages.success(request, 'Switched device "%s" %s!' % (device, 'on' if device.enabled else 'off'))
    
    return HttpResponseRedirect(reverse('bawebauth.views.show_device', kwargs={'device_id': device.id}))

@login_required
def delete_device(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)
    device.delete()
    
    messages.success(request, 'Deleted device "%s" from your Dashboard!' % device)
    
    template_values = {
        'devices': devices,
    }

    return render_to_response('show_dashboard.html', template_values, context_instance=RequestContext(request))

@login_required
def delete_device_ask(request, device_id):
    devices = Device.objects.all().filter(user=request.user).order_by('name')
    device = get_object_or_404(Device, user=request.user, id=device_id)

    button = '<a class="ym-button ym-delete float-right" href="%s" title="Yes">Yes</a>' % reverse('bawebauth.views.delete_device', kwargs={'device_id': device.id})     
    messages.warning(request, '%sDo you want to delete device "%s"?' % (button, device))
    
    template_values = {
        'devices': devices,
    }

    return render_to_response('show_dashboard.html', template_values, context_instance=RequestContext(request))

bawebauth/apps/bawebauth/templates/base.html
{% extends "yaml.html" %}
{% load compress %}

{% block title %}BaWebAuth{% endblock %}

{% block css %}
{% compress css %}
{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}navigation/hlist.css" />
  {% if LANGUAGE_BIDI %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}add-ons/rtl-support/navigation/hlist-rtl.css" />
  {% endif %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}forms/gray-theme.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}screen/typography.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}screen/screen-FULLPAGE-layout.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}screen/bawebauth.css" />
{% endcompress %}
{% endblock %}

{% block js %}
{% compress js %}
{{ block.super }}
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.8.3.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.9.2.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.yamlcss.button.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.datetime.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/highstock.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/zerotimeout.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/chart.usage.js"></script>
  <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-2841986-10', 'auto');
    ga('send', 'pageview');
  </script>
{% endcompress %}
{% endblock %}}

{% block extra-head %}
  <meta name="generator" content="Django" />
  <meta name="robots" content="index, follow, noarchive" />
  <meta name="keywords" content="bawebauth" />
  <meta name="revisit-after" content="1 days" />
  <meta name="google-site-verification" content="VSCgr9QgLsfBKZcLKIee8oP5Vay4hLuhwFcCBnEyAI4" />
{% endblock %}

{% block header %}
  <h1>BaWebAuth</h1>
{% endblock %}

{% block footer %}
  <p>Developed by <a href="http://www.marc-hoersken.de/" title="Marc H&ouml;rsken">Marc H&ouml;rsken</a> | Layout based on <a href="http://www.yaml.de">YAML</a> | Powered by <a href="http://www.djangoproject.com/">Django</a> and <a href="http://redis.io/">Redis</a> | <a href="https://github.com/mback2k/django-bawebauth/">Source Code</a> on <a href="https://github.com/">Github</a></p>
{% endblock %}

bawebauth/apps/bawebauth/templates/show_dashboard.html
{% extends "base.html" %}
{% load jdatetime %}
{% load yamlform %}

{% block navigation %}
  <li><a href="{% url 'bawebauth:show_home' %}" title="Home">Home</a></li>
  {% if user.is_authenticated %}
  <li class="active"><strong>Dashboard</strong></li>
  <li><a href="{% url 'password_change' %}" title="Change Password">Change Password</a></li>
  {% endif %}
{% endblock %}

{% block content %}
  {% if device %}
  {% if device_edit_form %}
  <form action="{% url 'bawebauth:edit_device' device.id %}" method="post" class="ym-form ym-columnar">
    {% csrf_token %}
    <h6 class="ym-fbox-heading">Edit Device:</h6>
    {{ device_edit_form|yamlform }}
    <div class="ym-fbox-footer ym-fbox-button">
      <input class="ym-button ym-save ym-primary" type="submit" name="submit" value="Save Device" />
      <a class="ym-button ym-next" href="{% url 'bawebauth:show_dashboard' %}" title="Go Back">Go Back</a>
    </div>
  </form>
  {% else %}
  <a class="ym-button ym-next float-right" href="{% url 'bawebauth:show_dashboard' %}" title="Go Back">Go Back</a>
  <h3>{{ device.name }}</h3>
  <div class="chart usage" id="chart_usage_{{ device.id }}">
    <a href="{% url 'bawebauth:api_device_usages' device.id 'json' %}"></a>
    <noscript>
      <div class="box warning">
        <p>You need to enable JavaScript in order to see the traffic usage graph.</p>
      </div>
    </noscript>
  </div><br />
  {% endif %}
  {% endif %}
  <table class="bordertable">
    <tbody>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Last Activity</th>
        <th scope="col">Total Traffic</th>
        <th scope="col">Manage</th>
      </tr>
      {% for device in devices %}
      <tr>
        <td><a href="{% url 'bawebauth:show_device' device.id %}" title="{{ device.name }}">{{ device.name }}</a></td>
        <td>{% if device.last_usage and device.last_usage.crdate %}{{ device.last_usage.crdate|localedatetime }}{% else %}None{% endif %}</td>
        <td>{{ device.total|filesizeformat }}<br />{{ device.send|filesizeformat }} &uArr; | {{ device.received|filesizeformat }} &dArr;</td>
        <td>
          {% if device.active %}
          <a class="ym-button ym-edit" href="{% url 'bawebauth:edit_device' device.id %}" title="Edit">Edit</a>
          <a class="ym-button {% if not device.enabled %}ym-enable ym-success{% else %}ym-disable ym-warning{% endif %}" href="{% url 'bawebauth:switch_device' device.id %}" title="{% if not device.enabled %}Enable{% else %}Disable{% endif %}">{% if not device.enabled %}Enable{% else %}Disable{% endif %}</a>
          <a class="ym-button ym-delete ym-danger" href="{% url 'bawebauth:delete_device_ask' device.id %}" title="Delete">Delete</a>
          {% else %}
          <a class="ym-button ym-save ym-success" href="{% url 'bawebauth:switch_device' device.id %}" title="Activate">Activate</a>
          <a class="ym-button ym-delete ym-danger" href="{% url 'bawebauth:delete_device' device.id %}" title="Delete">Delete</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

bawebauth/apps/bawebauth/templates/show_home.html
{% extends "base.html" %}

{% block navigation %}
  <li class="active"><strong>Home</strong></li>
  {% if user.is_authenticated %}
  <li><a href="{% url 'bawebauth:show_dashboard' %}" title="Dashboard">Dashboard</a></li>
  <li><a href="{% url 'password_change' %}" title="Change Password">Change Password</a></li>
  {% endif %}
{% endblock %}

{% block content %}
  <p>This service allows you to view the traffic used at the DHBW Mannheim while using the BaWebAuth client.</p>
  <div class="chart usage" id="chart_usages">
    <a href="{% url 'bawebauth:api_usages' 'json' %}"></a>
    <noscript>
      <div class="box warning">
        <p>You need to enable JavaScript in order to see the traffic usage graph.</p>
      </div>
    </noscript>
  </div><br />
{% endblock %}